#!/usr/bin/python
#   Flytec/Brauniger Filesystem
#   Copyright (C) 2008  Tom Payne
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.


# TODO enable multi-threading
# TODO waypoint upload
# TODO fix route deletion
# TODO route upload
# TODO preferences application
# TODO invalidate some contents after delete


from __future__ import with_statement

try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO
from collections import defaultdict
from contextlib import contextmanager
import errno
import logging
import sys
import time
try:
    from xml.etree.cElementTree import ElementTree, TreeBuilder
except ImportError:
    from xml.etree.ElementTree import ElementTree, TreeBuilder
from zipfile import ZipFile, ZipInfo, ZIP_DEFLATED

import fuse

import filesystem
from flytec import Flytec


class File(filesystem.File):

    def __init__(self, flytec, keys, name):
        filesystem.File.__init__(self, name)
        self.flytec = flytec
        self._content = None
        self.keys = keys
        self.revs = defaultdict()

    def sync(self):
        if self._content is None or any(self.revs[k] != self.flytec.revs[k] for k in self.keys):
            self._content = self.flytec_content()
            for key in self.keys:
                self.revs[key] = self.flytec.revs[key]

    def getattr(self):
        self.sync()
        return filesystem.File.getattr(self)

    def content(self):
        self.sync()
        return self._content


class Directory(filesystem.Directory):

    def __init__(self, flytec, name):
        filesystem.Directory.__init__(self, name)
        self.flytec = flytec


@contextmanager
def tag(tb, name, attrs={}):
    tb.start(name, attrs)
    yield tb
    tb.end(name)


GPX_NAMESPACE = 'http://www.topografix.com/GPX/1/1'
GPX_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%SZ'


@contextmanager
def gpx_tag(tb):
    attrs = {
        'creator': 'http://code.google.com/p/flytecfs',
        'version': '1.1',
        'xmlns': GPX_NAMESPACE,
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        'xsi:schemaLocation': 'http://www.topografix.com/GPX/1/1 '
                              'http://www.topografix.com/GPX/1/1/gpx.xsd',
        }
    with tag(tb, 'gpx', attrs) as tb:
        yield tb


@contextmanager
def wptType_tag(tb, waypoint, name):
    lat = '%.8f' % (waypoint.lat / 60000.0)
    lon = '%.8f' % (waypoint.lon / 60000.0)
    with tag(tb, name, {'lat': lat, 'lon': lon}):
        with tag(tb, 'name'):
            tb.data(waypoint.long_name.rstrip())
        with tag(tb, 'ele'):
            tb.data(str(waypoint.alt))


@contextmanager
def rte_tag(tb, route, waypoint_get):
    with tag(tb, 'rte'):
        with tag(tb, 'name'):
            tb.data(route.name.rstrip())
        for routepoint in route.routepoints:
            waypoint = waypoint_get(routepoint.long_name)
            wptType_tag(tb, waypoint, 'rtept')


def write_xml(et, file, indent='\t', prefix=''):
    attrs = ''.join(' %s="%s"' % pair for pair in et.attrib.items())
    if et.getchildren():
        file.write('%s<%s%s>\n' % (prefix, et.tag, attrs))
        for child in et.getchildren():
            write_xml(child, file, indent, prefix + indent)
        file.write('%s</%s>\n' % (prefix, et.tag))
    elif et.text:
        file.write('%s<%s%s>%s</%s>\n' %
                   (prefix, et.tag, attrs, et.text, et.tag))
    else:
        file.write('%s<%s%s/>\n' % (prefix, et.tag, attrs))


class GPXFile(File):

    def flytec_content(self):
        string_io = StringIO()
        string_io.write('<?xml version="1.0" encoding="utf-8"?>\n')
        with gpx_tag(TreeBuilder()) as tb:
            self.gpx_content(tb)
        write_xml(ElementTree(tb.close()).getroot(), string_io)
        return string_io.getvalue()

    def gpx_content(self):
        pass


class MemoryFile(File):

    def __init__(self, flytec, name):
        File.__init__(self, flytec, ('memory',), name)
        self.st_size = 352
        self.st_blocks = (self.st_size + self.st_blksize - 1) / self.st_blksize

    def getattr(self):
        return self

    def read(self, size, offset):
        return self.flytec.memory(slice(offset, offset + size))


class RoutesDirectory(Directory):

    def content(self):
        for route in self.flytec.routes():
            yield RouteFile(self.flytec, route)
        yield RoutesFile(self.flytec, 'routes.gpx')


class RouteFile(GPXFile):

    def __init__(self, flytec, route):
        name = '%s.gpx' % route.name.rstrip()
        GPXFile.__init__(self, flytec, ('routes',), name)
        self.route = route

    def gpx_content(self, tb):
        rte_tag(tb, self.route, self.flytec.waypoint_get)

    def unlink(self):
        if not self.flytec.route_unlink(self.route):
            raise IOError, (errno.EPERM, None)


class RoutesFile(GPXFile):

    def __init__(self, flytec, name):
        GPXFile.__init__(self, flytec, ('routes',), name)

    def gpx_content(self, tb):
        for route in self.flytec.routes():
            rte_tag(tb, route, self.flytec.waypoint_get)


class SettingsDirectory(Directory):

    def __init__(self, flytec, name):
        Directory.__init__(self, flytec, name)
        self._content = []
        self._content.append(MemoryFile(self.flytec, '.memory'))

    def content(self):
        return iter(self._content)


class TracklogFile(File):

    def __init__(self, flytec, tracklog):
        File.__init__(self, flytec, (), tracklog.igc_filename)
        self.tracklog = tracklog
        self.st_ctime = time.mktime(tracklog.dt.timetuple())
        self.st_mtime = self.st_ctime + tracklog.duration.seconds
        self.st_atime = self.st_mtime

    def flytec_content(self):
        return self.flytec.tracklog_content(self.tracklog)

    def unlink(self):
        self.flytec.tracklog_unlink(self.tracklog)


class TracklogsDirectory(Directory):

    def content(self):
        for tracklog in self.flytec.tracklogs():
            yield TracklogFile(self.flytec, tracklog)
        yield TracklogsZipFile(self.flytec, 'tracklogs.zip')


class TracklogsZipFile(File):

    def __init__(self, flytec, name):
        File.__init__(self, flytec, ('tracklogs',), name)

    def flytec_content(self):
        string_io = StringIO()
        tracklogs = self.flytec.tracklogs()
        ctimes = (t.dt for t in tracklogs)
        self.st_ctime = time.mktime(min(ctimes).timetuple())
        mtimes = (t.dt + t.duration for t in tracklogs)
        self.st_mtime = time.mktime(max(mtimes).timetuple())
        self.st_atime = self.st_mtime
        zip_file = ZipFile(string_io, 'w', ZIP_DEFLATED)
        for tracklog in tracklogs:
            zi = ZipInfo(tracklog.igc_filename)
            zi.compress_type = ZIP_DEFLATED
            zi.date_time = (tracklog.dt + tracklog.duration).timetuple()[:6]
            zi.external_attr = 0444 << 16
            zip_file.writestr(zi, self.flytec.tracklog_content(tracklog))
        zip_file.close()
        return string_io.getvalue()


class WaypointsDirectory(Directory):

    def content(self):
        for waypoint in self.flytec.waypoints():
            yield WaypointFile(self.flytec, waypoint)
        yield WaypointsFile(self.flytec, 'waypoints.gpx')


class WaypointFile(GPXFile):

    def __init__(self, flytec, waypoint):
        name = '%s.gpx' % waypoint.long_name.rstrip()
        GPXFile.__init__(self, flytec, ('waypoints',), name)
        self.waypoint = waypoint

    def gpx_content(self, tb):
        wptType_tag(tb, self.waypoint, 'wpt')

    def unlink(self):
        if not self.flytec.waypoint_unlink(self.waypoint):
            raise IOError, (errno.EPERM, None)


class WaypointsFile(GPXFile):

    def __init__(self, flytec, name):
        GPXFile.__init__(self, flytec, ('waypoints',), name)

    def gpx_content(self, tb):
        for waypoint in self.flytec.waypoints():
            wptType_tag(tb, waypoint, 'wpt')


class FlytecRootDirectory(Directory):

    def __init__(self, filesystem):
        flytec = Flytec(filesystem.device)
        Directory.__init__(self, flytec, '')
        self._content = []
        self._content.append(RoutesDirectory(self.flytec, 'routes'))
        self._content.append(SettingsDirectory(self.flytec, 'settings'))
        self._content.append(TracklogsDirectory(self.flytec, 'tracklogs'))
        self._content.append(WaypointsDirectory(self.flytec, 'waypoints'))

    def content(self):
        return iter(self._content)


def main(argv):
    logging.basicConfig(level=logging.INFO)
    server = filesystem.Filesystem(FlytecRootDirectory,
                                   dash_s_do='setsingle',
                                   usage=fuse.Fuse.fusage)
    server.device = '/dev/ttyUSB0'
    server.parser.add_option(mountopt='device',
                             metavar='PATH',
                             help='set device')
    server.parse(args=argv, values=server, errex=1)
    if server.fuse_args.mount_expected():
        server.main()


if __name__ == '__main__':
    main(sys.argv)
